from datetime import datetime, timedelta
import random

MOCK_TRANSACTIONS = [
    # --- Clearly suspicious ---
    {
        "user_id": "USR-001",
        "amount": 95000.00,
        "currency": "USD",
        "trade_type": "buy",
        "asset": "BTC",
        "ip_address": "185.220.101.45",
        "country": "RU",
        "timestamp": datetime.utcnow() - timedelta(hours=3),
        "status": "pending",
    },
    {
        "user_id": "USR-002",
        "amount": 47500.00,
        "currency": "USD",
        "trade_type": "sell",
        "asset": "BTC",
        "ip_address": "185.220.101.45",   # same IP as above — geo anomaly
        "country": "RU",
        "timestamp": datetime.utcnow() - timedelta(hours=3) + timedelta(minutes=2),
        "status": "pending",
    },
    {
        "user_id": "USR-003",
        "amount": 250000.00,
        "currency": "EUR",
        "trade_type": "buy",
        "asset": "ETH",
        "ip_address": "10.0.0.99",
        "country": "IR",
        "timestamp": datetime.utcnow().replace(hour=3, minute=15),
        "status": "pending",
    },
    {
        "user_id": "USR-004",
        "amount": 12500.00,
        "currency": "USD",
        "trade_type": "buy",
        "asset": "EUR/USD",
        "ip_address": "92.118.160.12",
        "country": "CN",
        "timestamp": datetime.utcnow() - timedelta(hours=1),
        "status": "pending",
    },
    {
        "user_id": "USR-004",
        "amount": 12400.00,
        "currency": "USD",
        "trade_type": "sell",
        "asset": "EUR/USD",
        "ip_address": "92.118.160.12",
        "country": "CN",
        "timestamp": datetime.utcnow() - timedelta(hours=1) + timedelta(minutes=3),
        "status": "pending",
    },
    {
        "user_id": "USR-005",
        "amount": 500000.00,
        "currency": "USD",
        "trade_type": "buy",
        "asset": "BTC",
        "ip_address": "77.88.21.34",
        "country": "KP",
        "timestamp": datetime.utcnow() - timedelta(hours=5),
        "status": "pending",
    },
    # --- Borderline suspicious ---
    {
        "user_id": "USR-006",
        "amount": 11000.00,
        "currency": "USD",
        "trade_type": "buy",
        "asset": "ETH",
        "ip_address": "203.0.113.5",
        "country": "NG",
        "timestamp": datetime.utcnow() - timedelta(hours=6),
        "status": "pending",
    },
    {
        "user_id": "USR-007",
        "amount": 8900.00,
        "currency": "GBP",
        "trade_type": "sell",
        "asset": "GBP/JPY",
        "ip_address": "198.51.100.22",
        "country": "GB",
        "timestamp": datetime.utcnow() - timedelta(hours=2),
        "status": "pending",
    },
    # --- Clearly clean ---
    {
        "user_id": "USR-008",
        "amount": 500.00,
        "currency": "USD",
        "trade_type": "buy",
        "asset": "ETH",
        "ip_address": "192.168.1.10",
        "country": "US",
        "timestamp": datetime.utcnow() - timedelta(hours=4),
        "status": "pending",
    },
    {
        "user_id": "USR-009",
        "amount": 1200.00,
        "currency": "EUR",
        "trade_type": "sell",
        "asset": "BTC",
        "ip_address": "192.168.1.11",
        "country": "DE",
        "timestamp": datetime.utcnow() - timedelta(hours=7),
        "status": "pending",
    },
    {
        "user_id": "USR-010",
        "amount": 350.00,
        "currency": "USD",
        "trade_type": "buy",
        "asset": "EUR/USD",
        "ip_address": "10.10.10.5",
        "country": "US",
        "timestamp": datetime.utcnow() - timedelta(hours=8),
        "status": "pending",
    },
    {
        "user_id": "USR-011",
        "amount": 2500.00,
        "currency": "USD",
        "trade_type": "sell",
        "asset": "ETH",
        "ip_address": "10.10.10.6",
        "country": "CA",
        "timestamp": datetime.utcnow() - timedelta(hours=9),
        "status": "pending",
    },
    {
        "user_id": "USR-012",
        "amount": 750.00,
        "currency": "GBP",
        "trade_type": "buy",
        "asset": "BTC",
        "ip_address": "172.16.0.1",
        "country": "GB",
        "timestamp": datetime.utcnow() - timedelta(hours=10),
        "status": "pending",
    },
    {
        "user_id": "USR-013",
        "amount": 4200.00,
        "currency": "USD",
        "trade_type": "sell",
        "asset": "GBP/USD",
        "ip_address": "172.16.0.2",
        "country": "AU",
        "timestamp": datetime.utcnow() - timedelta(hours=11),
        "status": "pending",
    },
    {
        "user_id": "USR-014",
        "amount": 980.00,
        "currency": "EUR",
        "trade_type": "buy",
        "asset": "ETH",
        "ip_address": "10.20.30.4",
        "country": "FR",
        "timestamp": datetime.utcnow() - timedelta(hours=12),
        "status": "pending",
    },
    {
        "user_id": "USR-015",
        "amount": 3100.00,
        "currency": "USD",
        "trade_type": "sell",
        "asset": "BTC",
        "ip_address": "10.20.30.5",
        "country": "US",
        "timestamp": datetime.utcnow() - timedelta(hours=13),
        "status": "pending",
    },
    {
        "user_id": "USR-016",
        "amount": 620.00,
        "currency": "USD",
        "trade_type": "buy",
        "asset": "EUR/USD",
        "ip_address": "10.20.30.6",
        "country": "SG",
        "timestamp": datetime.utcnow() - timedelta(hours=14),
        "status": "pending",
    },
    {
        "user_id": "USR-017",
        "amount": 1850.00,
        "currency": "EUR",
        "trade_type": "sell",
        "asset": "ETH",
        "ip_address": "10.20.30.7",
        "country": "NL",
        "timestamp": datetime.utcnow() - timedelta(hours=15),
        "status": "pending",
    },
    {
        "user_id": "USR-018",
        "amount": 430.00,
        "currency": "GBP",
        "trade_type": "buy",
        "asset": "BTC",
        "ip_address": "10.20.30.8",
        "country": "GB",
        "timestamp": datetime.utcnow() - timedelta(hours=16),
        "status": "pending",
    },
    {
        "user_id": "USR-019",
        "amount": 2200.00,
        "currency": "USD",
        "trade_type": "sell",
        "asset": "GBP/JPY",
        "ip_address": "10.20.30.9",
        "country": "JP",
        "timestamp": datetime.utcnow() - timedelta(hours=17),
        "status": "pending",
    },
]


def seed_database(db):
    from models import Transaction
    count = db.query(Transaction).count()
    if count > 0:
        return  # already seeded
    for tx_data in MOCK_TRANSACTIONS:
        tx = Transaction(**tx_data)
        db.add(tx)
    db.commit()
